### ISSUE TITLE
Loading error in latest dev

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#225] opened 2015-10-07 21:13 UTC
Starting with shower/core@269c173548f7e0c18415e1514920cfc6e40bd7e3, loading Shower in the browser gives
```
Uncaught Error: Required module "shower" can't be resolved
```
Versions before that compiled fine.

**Comment by pepelsbey** [comment] 2015-10-07 21:14
Yes, it’s a known issue caused by unfinished refactoring.
@zloylos could you please make it work again? :)

**Comment by RubenVerborgh** [comment] 2015-10-07 21:15
Thanks! Any ETA on v2.0 BTW? I'm a happy beta user :wink:

**Comment by pepelsbey** [comment] 2015-10-07 21:22
I wish I knew, I’m [using it myself](http://pepelsbey.net/pres/web-apps/) and pretty happy about it. But you know it takes more than just a happy author to release something: tests, documentation and I have to finish the new Material theme.

Let’s see if I can do it before the end of the year :)

**Comment by RubenVerborgh** [comment] 2015-10-07 22:28
Thanks! BTW, I'm working on a [Clear](https://github.com/RubenVerborgh/Shower-Clear) theme that I will use fot teaching. It has a strict look with long titles and limited colors. Just rebased on the latest version—wasn't easy :smile:

**Comment by pepelsbey** [comment] 2015-11-14 05:45
It’s fixed now.

**Closed by pepelsbey** 2015-11-14 05:45 UTC
Labels: bug
