### ISSUE TITLE
Swipe doesn't work with video

### ISSUE THREAD

**Issue by cornae** [shower/shower#119] opened 2013-01-22 12:50 UTC
When I'm playing HTML5 video that is the size of a slide on a slide, then slide navigation no longer works.

**Comment by thepian** [comment] 2015-08-04 23:10
And swipe gestures on trackpad.

**Comment by RubenVerborgh** [comment] 2016-02-20 12:09
Is #235 a duplicate of this one? Also, #235 suggests a fix.

**Comment by cornae** [comment] 2016-02-20 12:38
Looks like it yes

**Closed** 2019-02-08 19:15 UTC
Labels: bug
