### ISSUE TITLE
Failed to execute 'pushState' on 'History'

### ISSUE THREAD

**Issue by drnextgis** [shower/shower#227] opened 2015-11-14 05:29 UTC
I've downloaded shower.zip from starting page but when I open index.html in Chromium and try to switch to second slide - presentation automatically goes to list mode and I get error in console:

```
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///home/dr/tmp./index.html?full#Cover' cannot be created in a document with origin 'null'.
```

The same presentation works fine in Firefox.

**Comment by pepelsbey** [comment] 2015-11-14 05:44
It’s a known issue caused by the new Chrome (since 45 or so) security limitations: it’s not allowed anymore to manipulate history for `file:///` protocols. It could be easily solved by using local server: `python -m SimpleHTTPServer 8000`, for example. [There’s also a patch](https://github.com/shower/core/pull/22) removing History API usage from Shower’s core (replacing it with `localStorage` states), but it’s not merged yet, but it will be soon.

**Closed by pepelsbey** 2015-11-14 05:44 UTC
