### ISSUE TITLE
F5 issue

### ISSUE THREAD

**Issue by uyouthe** [shower/shower#291] opened 2017-01-29 11:54 UTC
When I press F5 or Shift + F5 (Windows 8.1, Chrome), the slides doesn't update. Instead of that, it switches to #cover slide and the whole presentation does not seem to be updated, I still have the old slides. But, when I push the Update button in browser, the page update happens as needed.

**Comment by pepelsbey** [comment] 2017-01-29 12:25
That’s by desing, [see shortcuts docs](https://github.com/shower/shower/blob/master/docs/shortcuts-en.md), here’s slightly redacted version:

- Start presentation from the current slide: Shift F5
- Start presentation from the first slide: F5
- Stop presentation: F5

**Comment by pepelsbey** [comment] 2017-01-29 12:30
But the question remains: is it expected behavior on Windows? I’ve been trying to replicate PowerPoint and Keynote shortcuts to make it comfortable for the ones who get used to such software. But it seems I went too far.

**Comment by uyouthe** [comment] 2017-01-29 12:49
F5 is usually stands for page update. When I'm using browser, I expect that I have typical browser behavior and hotkeys at any page, including Shower

Thanks!

**Comment by pepelsbey** [comment] 2017-01-30 22:50
Fixed in [2f0af4d](https://github.com/shower/core/commit/2f0af4d8660e683af386cde07a3ad38d19821df4), will release it shortly.

**Closed by pepelsbey** 2017-01-30 22:50 UTC

**Comment by bozaro** [comment] 2017-01-31 05:50
Look like you need also update documentation.

**Comment by pepelsbey** [comment] 2017-01-31 07:44
@bozaro, [done](https://github.com/shower/shower/blob/master/docs/shortcuts.md), thank you for reminder

**Comment by pepelsbey** [comment] 2017-02-01 08:39
FYI: after futher testing I reverted `Shift F5` shortcut for starting presentation from the current slide since it’s a standard way in PowerPoint and it doesn’t affect Windows browsers.
