### ISSUE TITLE
Black page at page refresh

### ISSUE THREAD

**Issue by markelog** [shower/shower#211] opened 2015-06-08 09:25 UTC
Go to http://shwr.me/?full#2 through chrome > 42 on osx machine, then refresh the page.

Not reproducible on chrome 42 or Opera (not yet anyway).

**Comment by pepelsbey** [comment] 2015-06-08 09:50
Known problem caused by [Chromium regression](https://code.google.com/p/chromium/issues/detail?id=492142#c10):

> Be careful: CSS pseudo-class :target is broken
> in the stable Chromium 43 (and browsers based on it)

https://twitter.com/pepelsbey_/status/606425799919595520

**Comment by pepelsbey** [comment] 2015-06-08 09:51
You can fix it by using `.active` class in your theme instead of `:target`

**Comment by pepelsbey** [comment] 2015-06-09 00:34
It seems [the bug is fixed](https://code.google.com/p/chromium/issues/detail?id=492142#c18), waiting for it to be rolled out with next Chromium updates.

**Comment by pepelsbey** [comment] 2015-06-30 12:18
It’s fixed in the current Chrome Canary 45.0.2444.0, hope to see it in stable in a couple of weeks or maybe a bit more.

**Closed by pepelsbey** 2015-06-30 12:18 UTC
Labels: bug
